name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Metrics
        with:
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        name: Diff history
        with:
          filename: metrics.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_lines_repositories_limit: 10000
          plugin_lines_sections: history
          plugin_lines_history_limit: 5
      - name: Comments
        uses: lowlighter/metrics@latest
        with:
          base: ""
          filename: metrics.comments.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_reactions: yes
          plugin_reactions_limit: 10000
          plugin_reactions_details: percentage

