name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Metrics
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: large
          base: header, activity, community
          base_indepth: yes
          repositories: 500
          repositories_affiliations: collaborator, owner
          repositories_forks: yes
          plugin_reactions: yes
          plugin_reactions_limit: 10000
          plugin_reactions_details: percentage
          plugin_gists: yes
          plugin_lines: yes
          plugin_lines_repositories_limit: 10000
          plugin_lines_sections: history
          plugin_lines_history_limit: 5
